### ISSUE TITLE
Unable to disable modular menu

### ISSUE THREAD

**Issue by spencergoldade** [trilbymedia/grav-skeleton-typhoon-onepage#1]
**Problem**
Unable to disable modular menu in Typhoon skeleton/theme

**User Story**
As a Typhoon user, I want to be able to start with the One-Page template but disable the modular menu, because it is just a great starting point for me and I don't necessarily want the one-page format.

**Steps to Reproduce**
1. Install the Typhoon Skeleton
2. Navigate to the settings for the Modular Homepage
3. Under "Header Configuration" toggle on the override for "Modular On-Page Menu" and set toggle to "No"
4. Save
5. Setting reverts to this setting being off, unable to override

**Notes**
I assume this may be due to a conflict between these settings and the page template.

**Comment by rhukster** [comment]
Easy fix...

In Typhoon's `blueprints/modular.yaml` change line 11 to:

```yaml
                header.onpage_menu:
```

FYI, for future Typhoon related issues, please post them on github.com/getgrav/grav-premium-issues/issues

Cheers!
